### ISSUE TITLE
PVSS sometimes misses the ending data of a recording

### ISSUE THREAD

**Issue by CrepeGoat** [MideTechnology/endaq-python-calc#11]
The PVSS is partially implemented via biquad filter; unfortunately the biquad filter stops at the last sample, when in some cases it may otherwise generate critical data by running the remainder of the filter over zeros.

**Comment by shanlyMIDE** [comment]
Enabling padding would be very helpful to eliminate this weird low frequency stuff that occurs which I always thought was a result of the filter (it isn't). Here is a shock signal:
![image](https://user-images.githubusercontent.com/35080650/133651510-e6ba5df4-15f7-4d46-9416-3b23983b28f8.png)

It is 2000 data points long with a total time of 0.1999 seconds. 

Here is the integrated velocity: 

![image](https://user-images.githubusercontent.com/35080650/133651814-157578ee-5047-4261-ac0e-1971fcf73e9f.png)


Here is the PVSS with no padding:
![image](https://user-images.githubusercontent.com/35080650/133651953-6409a92a-0afd-4d34-b8a4-4856b9d4a461.png)

Here is it with 1,000 points zero padding: 
![image](https://user-images.githubusercontent.com/35080650/133652099-3c5a4e46-a37a-400c-b816-78bfb1541cf3.png)

Here is it with 10,000 points zero padding:
![image](https://user-images.githubusercontent.com/35080650/133652207-4d61553f-1688-4ab9-adc5-8d80294b704b.png)

**Comment by shanlyMIDE** [comment]
For reference, here is the code I was using to add the padding:
~~~
pad_amount = 10000

df_zero = pd.DataFrame(np.zeros((pad_amount,3)))
df_zero.columns = df_accel.columns
d_t = (df_accel.index[-1] - df_accel.index[0])/(df_accel.shape[0]-1)

times = np.arange(df_accel.index[-1]+d_t, df_accel.index[-1]+d_t*pad_amount, d_t)
df_zero.index = times

df_padded = pd.concat([df_accel_filt,
                       df_zero],axis=0)
~~~
