### ISSUE TITLE
Function to get log spaced frequencies for pvss calculation

### ISSUE THREAD

**Issue by shanlyMIDE** [MideTechnology/endaq-python-calc#32]
The pvss function has a parameter to define which frequencies are calculated. I'd like to have a function to calculate these frequencies given a time indexed dataframe so that the last frequency automatically ends at/before the nyquist. Here's one I wrote.

~~~
def get_log_freqs(df,init_freq=1,bins_per_octave=12):
  """Given a timebased dataframe, return a log spaced frequency array up to the Nyquist frequency"""
  fs = (df.shape[0]-1)/(df.index[-1]-df.index[0])
  return 2 ** np.arange(np.log2(init_freq),
                        np.log2(fs/2),
                        1/bins_per_octave)
~~~

**Comment by shanlyMIDE** [comment]
This may deserve another issue... but it would be helpful to get the sample rate from these time based dataframes as another simple function.

**Comment by CrepeGoat** [comment]
> This may deserve another issue... but it would be helpful to get the sample rate from these time based dataframes as another simple function.

it *would* be helpful; internally I've been copy/pasting the code for such a function around because it's easier, but it should exist in a dedicated function somewhere.

Steve in case you need something in the short-term, I've pasted this code chunk below:
```python
dt = (df.index[-1] - df.index[0]) / (len(df.index) - 1)
if isinstance(dt, (np.timedelta64, pd.Timedelta)):
    dt = dt / np.timedelta64(1, "s")
```
